/**
 * Centralized icon exports — wraps lucide-react with consistent size/color defaults.
 * Usage: import { UsersIcon, MusicIcon } from '../icons'
 */
export {
  // Navigation
  LayoutDashboard as DashboardIcon,
  Users as UsersIcon,
  Mic2 as ArtistsIcon,
  Music4 as ContentIcon,
  Megaphone as BroadcastIcon,
  Settings as SystemIcon,
  DollarSign as FinanceIcon,
  ShieldAlert as ModerationIcon,
  MonitorPlay as AdsIcon,

  // Actions
  Search as SearchIcon,
  Plus as PlusIcon,
  Pencil as EditIcon,
  Trash2 as DeleteIcon,
  RefreshCw as RefreshIcon,
  Send as SendIcon,
  LogOut as LogoutIcon,
  Bell as BellIcon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  Copy as CopyIcon,
  Check as CheckIcon,
  X as XIcon,
  ChevronLeft as PrevIcon,
  ChevronRight as NextIcon,
  Filter as FilterIcon,
  MoreVertical as MoreIcon,
  ExternalLink as ExternalLinkIcon,
  Play as PlayIcon,
  Pause as PauseIcon,
  StopCircle as StopIcon,

  // Status
  CheckCircle2 as CheckCircleIcon,
  XCircle as XCircleIcon,
  AlertTriangle as WarningIcon,
  AlertCircle as AlertIcon,
  Info as InfoIcon,
  Loader2 as SpinnerIcon,

  // Content
  Music as MusicIcon,
  Video as VideoIcon,
  Image as ImageIcon,
  FileText as FileIcon,
  Radio as LiveIcon,
  MessageSquare as MessageIcon,
  Heart as HeartIcon,
  Star as StarIcon,
  Globe as GlobeIcon,
  Zap as ZapIcon,
  TrendingUp as TrendingUpIcon,
  BarChart2 as BarChartIcon,
  PieChart as PieChartIcon,
  Activity as ActivityIcon,
  Target as TargetIcon,
  Award as AwardIcon,
  Verified as VerifiedIcon,
  Shield as ShieldIcon,
  Lock as LockIcon,
  Unlock as UnlockIcon,
  Server as ServerIcon,
  Database as DatabaseIcon,
  Cpu as CpuIcon,
  HardDrive as HardDriveIcon,
  Wifi as WifiIcon,
  WifiOff as WifiOffIcon,

  // Finance
  CreditCard as CreditCardIcon,
  Wallet as WalletIcon,
  ArrowUpRight as ArrowUpIcon,
  ArrowDownRight as ArrowDownIcon,
  BadgeDollarSign as BadgeDollarIcon,
  Banknote as BanknoteIcon,
  Receipt as ReceiptIcon,

  // Ads
  Megaphone as MegaphoneIcon,
  MousePointerClick as ClickIcon,
  Layers as PlacementIcon,
  Calendar as CalendarIcon,
  Clock as ClockIcon,
  Users2 as AudienceIcon,
  Flag as FlagIcon,
  Briefcase as BriefcaseIcon,
} from 'lucide-react';
